name: Build Wheels

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
        pyver: ["3.8", "3.9", "3.10"]
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.pyver }}
        
      - name: Setup Mamba
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          activate-environment: "build"
          python-version: ${{ matrix.pyver }}
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          add-pip-as-python-dependency: true
          auto-activate-base: false
          
      - name: Install Dependencies
        run: |
          mamba install -y 'cuda' -c 'nvidia/label/cuda-11.7.0'
          python -m pip install build wheel torch==2.0.1+cu117 safetensors sentencepiece ninja --extra-index-url https://download.pytorch.org/whl/cu117
        
      - name: Build Wheel
        id: build-wheel
        run: |
          if ($(Get-Content 'setup.py' -raw) -match 'version = "(\d+\.(?:\d+\.?)*)" \+ \(') {echo $($Matches[1]); echo "PACKAGE_VERSION=workflowtest" >> "$env:GITHUB_OUTPUT"} else {echo '::error file=build-wheels-release.yml,line=41::Could not parse version from setup.py! You must upload wheels manually!'; echo "PACKAGE_VERSION=None" >> "$env:GITHUB_OUTPUT"}
          $env:CUDA_PATH = $env:CONDA_PREFIX
          $env:CUDA_HOME = $env:CONDA_PREFIX
          if ($IsLinux) {$env:LD_LIBRARY_PATH = $env:CONDA_PREFIX + '/lib:' + $env:LD_LIBRARY_PATH}
          $env:TORCH_CUDA_ARCH_LIST = '6.0 6.1 7.0 7.5 8.0 8.6+PTX'
          python -m build -n --wheel
        
      - uses: actions/upload-artifact@v3
        with:
          name: 'wheels'
          path: ./dist/*.whl
          
      - name: Upload files to a GitHub release
        if: steps.build-wheel.outputs.PACKAGE_VERSION != 'None'
        uses: svenstaro/upload-release-action@2.6.1
        with:
          file: ./dist/*.whl
          tag: ${{ steps.build-wheel.outputs.PACKAGE_VERSION }}
          file_glob: true
          overwrite: true
          make_latest: false
          release_name: ${{ steps.build-wheel.outputs.PACKAGE_VERSION }}
          body: "Wheels are compiled with CUDA 11.7 for Windows and Linux x64"